# Generated by Django 4.0.4 on 2023-02-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_univ_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='univ',
            name='total_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='univ',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='univ',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d'),
        ),
    ]
