# Generated by Django 4.0.4 on 2023-02-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_univ_total_score_user_univ_alter_univ_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='univ',
            field=models.CharField(max_length=50),
        ),
    ]
