# Generated by Django 4.0.4 on 2023-02-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_question_ans_question_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ans',
            field=models.IntegerField(default=False),
        ),
    ]
